---
apiVersion: v1
kind: Secret
metadata:
  name: appordersval-repo
  namespace: devhub
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/devhub-mad/appordersval-backend-gitops
